/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    {
      type: "doc",
      label: "Introduction",
      id: "index",
    },
    {
      type: "category",
      label: "Question types",
      items: [{ type: "autogenerated", dirName: "question-types" }],
    },
    {
      type: "category",
      label: "Embed sessions",
      items: [{ type: "autogenerated", dirName: "embed-sessions" }],
    },
    {
      type: "category",
      label: "LMS integrations",
      items: [{ type: "autogenerated", dirName: "lms" }],
    },
    {
      type: "category",
      label: "Importing",
      items: [{ type: "autogenerated", dirName: "importing" }],
    },
    {
      type: "category",
      label: "Compliance",
      items: [{ type: "autogenerated", dirName: "compliance" }],
    },
  ],
};

try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const fs = require("fs");
  if (fs.statSync("./docs/rest-api/sidebar.ts")) {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const RestApiSidebar = require("./docs/rest-api/sidebar");
    RestApiSidebar.splice(1, 0, [
      {
        type: "doc",
        id: "rest-api/oauth",
      },
    ]);
    // @ts-expect-error callable
    sidebars.sidebar.push({
      type: "category",
      label: "REST API reference",
      items: RestApiSidebar,
    });
  }
} catch (e) {
  console.log(e);
}

export default sidebars;
