/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    {
      type: "doc",
      label: "Introduction",
      id: "index",
    },
    {
      type: "category",
      label: "Question types",
      items: [{ type: "autogenerated", dirName: "question-types" }],
    },
    {
      type: "category",
      label: "LMS integrations",
      items: [{ type: "autogenerated", dirName: "lms" }],
    },
    {
      type: "category",
      label: "Importing",
      items: [{ type: "autogenerated", dirName: "importing" }],
    }
  ],
};

try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const fs = require("fs");
  if (fs.statSync("./docs/rest-api/sidebar.ts")) {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const RestApiSidebar = require("./docs/rest-api/sidebar");
    // @ts-expect-error callable
    sidebars.sidebar.push({
      type: "category",
      label: "REST API reference",
      items: RestApiSidebar,
    });
  }
} catch (e) {
  console.log(e);
}

export default sidebars;
